#undef ONESHOT_TIMEOUT
#define ONESHOT_TIMEOUT 1000

#define USB_SUSPEND_WAKEUP_DELAY 0
#define AUTO_SHIFT_MODIFIERS
#define AUTO_SHIFT_TIMEOUT 180
#define NO_AUTO_SHIFT_TAB
#define NO_AUTO_SHIFT_SPECIAL
#define NO_AUTO_SHIFT_NUMERIC
#define HOLD_ON_OTHER_KEY_PRESS
#define SERIAL_NUMBER "OQPyr/bvJQ4x"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

#define CAPS_LOCK_STATUS
#define VOYAGER_USER_LEDS
